# The URL the site will be built for
base_url = "https://baldassari.xyz"

# Author
author = "François Baldassari"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Which theme to use
theme = "no-style-please"

# Enable Atom Feed
generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
list_pages = true
no_list_date = true

footer_nav = [
    { name = "Home", url = "/" },
    { name = "RSS", url = "/atom.xml" },
]

